labels:
- name: enhancement
  description: New feature or request
  color: 84b6eb
- name: help wanted skiff
  description: Extra attention is needed
  color: "008672"
- name: new_test_label
  description: test_label
  color: 0E8A16
- name: question
  description: Further information is requested
  color: cc317c
- name: tf bug
  description: Something isn't working
  color: fc2929
repos:
- name: YaroslavGankov/my-actions
  labels:
  - enhancement
  - help wanted skiff
  - new_test_label
  - question
  - tf bug
