#standart file with labels. Don't automatic assign, just set in repo
labels:
- name: help wanted skiff
  description: Extra attention is needed
  color: "008672"
- name: tf bug
  description: Something isn't working
  color: fc2929
- name: enhancement
  description: New feature or request
  color: 84b6eb
- name: question
  description: Further information is requested
  color: cc317c
repos:
- name: YaroslavGankov/my-actions
  labels:
  - help wanted skiff
  - tf bug
  - enhancement
  - question