labels:
- name: enhancement
  description: New feature or request
  color: 84b6eb
- name: help wanted skiff
  description: Extra attention is needed
  color: "008672"
- name: infrastructure
  description: ""
  color: ededed
- name: question
  description: Further information is requested
  color: cc317c
- name: tf bug
  description: Something isn't working
  color: fc2929
- name: tf-live-datawarehouse
  description: ""
  color: ededed
- name: work in progress
  description: ""
  color: E4D2E8
repos:
- name: YaroslavGankov/my-actions
  labels:
  - enhancement
  - help wanted skiff
  - infrastructure
  - question
  - tf bug
  - tf-live-datawarehouse
  - work in progress
