labels:
- name: infrastructure
  description: ""
  color: ededed
- name: tf-live-datawarehouse
  description: ""
  color: ededed
- name: work in progress
  description: ""
  color: E4D2E8
repos:
- name: YaroslavGankov/my-actions
  labels:
  - infrastructure
  - tf-live-datawarehouse
  - work in progress
