name: "Test Cache 1"

on:
  workflow_dispatch:
  
jobs:
  terraform1:
    name: "test1"
    runs-on: ubuntu-latest
    env:
      PATH_TERRAFORM_PROVIDERS: .terraform/providers/
      TF_ORIGIN_PROVIDER: providers.tf
      WORKING_DIRECTORY: tf-origins #my dir with tf-files
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }} 
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: true
          terraform_version: 1.2.5

      - name: ls -la
        run: |
          pwd
          echo "HOME:"
          #/home/runner
          echo $HOME
          echo "env.HOME:"
          echo ${{ env.HOME }}
          echo ${{ runner.temp }}
          echo "tree:"
          #/home/runner/work/_temp
          tree ${{ runner.temp }}
          echo ${{ join(env.WORKING_DIRECTORY, env.TF_ORIGIN_PROVIDER) }}
          echo ${{ join('$WORKING_DIRECTORY/$TF_ORIGIN_PROVIDER') }}
          echo ${{ join('"$WORKING_DIRECTORY/$TF_ORIGIN_PROVIDER"') }}
          echo ${{ format('{0}{1}{2}',env.WORKING_DIRECTORY,'/',env.TF_ORIGIN_PROVIDER) }}
          echo -e ":.terraform:\n"
          ls -la .terraform
          echo -e "\n$PATH_TERRAFORM_PROVIDERS"
          ls -la $PATH_TERRAFORM_PROVIDERS
          echo -e "\ndu -s :\n"
          du -s .terraform
        continue-on-error: true

      #добавляем файл настройки для плагинов
      
      - name: Added .terraformrc
        run: echo 'plugin_cache_dir   = "$HOME/.terraform.d/plugin-cache"' >> $HOME/.terraformrc
      
      #сначала кешируем файл providers.tf и сверяем его
      - name: Check file providers.tf
        id: check_file_origin_providers_tf
        uses: actions/cache@v3
        with:
          ##working variant:
          #path: tf-origins/providers.tf
          #path: ${{ env.WORKING_DIRECTORY, '/', env.TF_ORIGIN_PROVIDER} ) }}
          path: ${{ format('{0}{1}{2}',env.WORKING_DIRECTORY,'/',env.TF_ORIGIN_PROVIDER) }}
          #key: ${{ runner.os }}-${{ hashFiles('tf-origins/providers.tf') }}
          key: ${{ runner.os }}-${{ hashFiles(format('{0}{1}{2}',env.WORKING_DIRECTORY,'/',env.TF_ORIGIN_PROVIDER)) }}-4

      #если файл providers.tf не тот, то запускаем Init
      - name: First Terraform Init
        if: ${{ steps.check_file_origin_providers_tf.outputs.cache-hit != 'true' }}
        id: first_init
        run: |
          echo "startuem"
          terraform init
          sleep 5

      - name: ls -la
        run: |
          tree -a $HOME
          tree -a $WORKING_DIRECTORY
        continue-on-error: true

      #кешируем провайдеры
      - name: Cache_Terraform
        id: cache_providers
        uses: actions/cache@v3
        with:
          #path: ${{ runner.temp }}/_github_home/.terraform.d/plugin-cache #if use .terraformrc with cache
          path: |
            ${{ format('{0}{1}{2}',env.WORKING_DIRECTORY,'/',env.PATH_TERRAFORM_PROVIDERS) }}
            ${{ format('{0}{1}',env.HOME,'/.terraform.d/plugin-cache') }}
          #key checks file providers.tf and cached files from path '.terraform/providers/**'. If any of them was changed, new cache will be created
          key: ${{ runner.os }}-providers-${{ hashFiles(format('{0}{1}{2}',env.WORKING_DIRECTORY,'/',env.TF_ORIGIN_PROVIDER)) }}-4
          #key: ${{ runner.os }}-providers-${{ hashFiles('tf-origins/providers.tf') }}

      - name: ls -la
        run: |
          echo "tree HOME:"
          tree $HOME
          echo "ls -la HOME:"
          ls -la $HOME
          tree -a $WORKING_DIRECTORY
          echo -e ":ls -la:\n"
          ls -la ${{ runner.temp }}/_github_home/.terraform.d/plugin-cache
          ls -la .
          echo -e ":.terraform:\n"
          ls -la .terraform
          echo -e ":$PATH_TERRAFORM_PROVIDERS:\n"
          ls -la $PATH_TERRAFORM_PROVIDERS
          echo -e "\ntest -d:\n"
          [[ ! -d $PATH_TERRAFORM_PROVIDERS ]] ; echo $?
        continue-on-error: true

      #Init с кешированными данными
      - name: Terraform Init
        if: ${{ steps.first_init.outcome != 'success' }}
        id: init
        run: |
          echo "run terraform init with cached data"
          terraform init
          sleep 5
      #тут, наверное, нужно добавить какой-нибудь output для контроля, ведь этот шаг будет запускаться в случае аварии с кешем или с Init выше
    
      - name: ls -la
        run: |
          echo -e ":.terraform:\n"
          ls -la .terraform
          echo -e ":$PATH_TERRAFORM_PROVIDERS:\n"
          ls -la .terraform/providers/
        continue-on-error: true

      - name: Terraform Plan
        # id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
