name: "Terraform"

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #      - 'workspaces/tf-live-shared/**'
  #      - '.github/workflows/tf-live-shared.yml'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #      - 'workspaces/tf-live-shared/**'
  #      - '.github/workflows/tf-live-shared.yml'

jobs:
  terraform1:
    name: "main-job-ololo"
    runs-on: ubuntu-latest
    env:
      PATH_TERRAFORM_PROVIDERS: .terraform/providers/
      TF_ORIGIN_PROVIDER: providers.tf
      WORKING_DIRECTORY: tf-origins/
    defaults:
      run:
        working-directory: tf-origins/ #my tf-files
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: true
          terraform_version: 1.2.5

      - name: ls -la
        run: |
          pwd
          echo -e ":.terraform:\n"
          ls -la .terraform
          echo -e "\n$PATH_TERRAFORM_PROVIDERS"
          ls -la $PATH_TERRAFORM_PROVIDERS
          echo -e "\ntest -d:\n"
          [[ ! -d $PATH_TERRAFORM_PROVIDERS ]] ; echo $?
        continue-on-error: true

      # - name: Check file providers.tf
      #   uses: actions/cache@v3
      #   with:
      #     path: $TF_ORIGIN_PROVIDER
      #     key: ${{ runner.os }}-${{ hashFiles(env.WORKING_DIRECTORYenv.TF_ORIGIN_PROVIDER) }}

      - name: check path
        id: check_path
        run: ls -la $PATH_TERRAFORM_PROVIDERS
        continue-on-error: true
      
      - name: First Terraform Init
        if: ${{ steps.check_path.outcome == 'failure' }}
        #if: ${{ echo $([ -d snap ] ; echo $?) }}        
        id: first_init
        run: |
          echo "startuem"
          terraform init

      - name: Cache_Terraform_Providers
        id: cache_providers
        uses: actions/cache@v3
        with:
          path: $PATH_TERRAFORM_PROVIDERS
          #key checks file providers.tf and cached files from path '.terraform/providers/**'. If any of them was changed, new cache will be created
          #key: ${{ runner.os }}-providers-${{ hashFiles('providers.tf') }}-${{ hashFiles('.terraform/providers/') }}
          key: ${{ runner.os }}-providers-${{ hashFiles('tf-origins/providers.tf') }}

      - name: ls -la
        run: |
          echo -e ":.terraform:\n"
          ls -la .terraform
          echo -e ":$PATH_TERRAFORM_PROVIDERS:\n"
          ls -la $PATH_TERRAFORM_PROVIDERS
          echo -e "\ntest -d:\n"
          [[ ! -d $PATH_TERRAFORM_PROVIDERS ]] ; echo $?
        continue-on-error: true

      - name: Terraform Init
        if: ${{ steps.cache_providers.outputs.cache-hit != 'true' }}
        id: init
        run: terraform init

      - name: ls -la
        run: |
          echo -e ":.terraform:\n"
          ls -la .terraform
          echo -e ":$PATH_TERRAFORM_PROVIDERS:\n"
          ls -la .terraform/providers/

      - name: Terraform Plan
        # id: plan
        run: terraform plan -no-color -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false