# This is a basic workflow to help you get started with Actions

name: Test_Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: cache-test1
        uses: actions/cache@v3
        with:
          path: |
            test2/file2.txt
            test2/file1.txt
          key: ${{ runner.os }}-ololo-${{ hashFiles('test/indicator-file.txt') }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: ls -la 1
        run: |
          ls -la
          ls -la test
          ls -la test2
      
      - name: cat file1 and file 2
        run: |
          cat test2/file1.txt
          cat test2/file2.txt
          cat test2/file3.txt
          cat test2/file4.txt
        
      # - name: clone repo
      #   uses: actions/checkout@v3
        
      - name: ls -la 2
        run: |
          ls -la test
          ls -la test2
