name: "Labels_From_File"

on:
  workflow_dispatch:
  push:
#    branches: [ main ]
    paths:
      - .github/labels.yml

jobs:
  assign_labels:
    name: "Define_labels_from_file"
    runs-on: ubuntu-latest
    env:
      LABELS_FILE: .github/labels.yml
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync labels with dryrun option
        if: github.ref != 'refs/heads/main'
        uses: b4b4r07/github-labeler@master
        with:
          dryrun: 'true'
          config: ${{ env.LABELS_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: labeler
        
      - name: Post github-labeler command result to GitHub comment
        uses: b4b4r07/action-github-comment@master
        if: steps.labeler.outputs.result && github.ref != 'refs/heads/main'
        with:
          body: |
            ## github-labeler result
            ```
            ${{ steps.labeler.outputs.result }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG: trace

      - name: Define labels from file to repo
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: b4b4r07/github-labeler@master
        with:
          config: ${{ env.LABELS_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
