#test labelling
name: "Labels_From_File"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - .github/labels.yml

jobs:
  assign_labels:
    name: "Assign_labels_from_file"
    runs-on: ubuntu-latest
    env:
      LABELS_FILE: .github/labels.yml
    steps:

      - name: Checkout
        #uses: actions/checkout@1.0.0
        uses: actions/checkout@v3

      - name: Sync labels
        uses: b4b4r07/github-labeler@master
        with:
          config: ${{ env.LABELS_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
