name: GitHub Super Linter
on:
  pull_request:
    branches: [ main ]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4.9.6
        id: lint
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSON: true
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_TERRAFORM_TFLINT: true
          TERRAFORM_TFLINT_CONFIG_FILE: .tflint.hcl
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
