#working version with service
name: Test nginx
on:
  workflow_dispatch:
  # push:
  #   branches: [ master, main ]

jobs:
  build:
    name: "Nginx"
    runs-on: ubuntu-latest
    services:
      nginx-service:
        image: nginx
        ports: 
          - 60-100:60-100
    
    steps:
      - name: debug telnet
        run: |
          telnet localhost 80
        continue-on-error: true
    
      - name: debug curl
        run: |
          curl localhost:80
          cat /notexistfile
        #continue-on-error: true
      
      - name: ololo step
        if: failure()
        run: echo "ololo1"
        continue-on-error: true 
