name: Test_Matrix_Strategy
on:
  workflow_dispatch:

#     ----------------------------------------------------------------------------------------------
# #запускаются все Jobs параллельно и выполняются параллельно. Выполнились все Job
# concurrency:
#   group: ${{ github.job.name == 'example_matrix' }}
#   cancel-in-progress: true

#запускаются все Jobs параллельно и выполняются параллельно. Выполнились все Job
concurrency:
  group: example_matrix


jobs:
  testing_concurrency:
#     ----------------------------------------------------------------------------------------------
#     #запускаются 2 Jobs параллельно и выполняются параллельно, 2 Jobs отменяются и не запускаются
#     concurrency:
#       group: example_matrix
#       cancel-in-progress: true

#     ----------------------------------------------------------------------------------------------
#     #поведение разное
#     #поведение 1. запускаются 1 Job, 1 Job отменяется, 2 Jobs выполняются после выполнения первой Job (одна за другой)
#     #поведение 2. запускаются 2 Jobs параллельно и выполняются параллельно,...
#     #...2 Jobs выполяются после выполнения первых 2 Jobs и тоже выполняются параллельно
#     #поведение 3. запускаются 1 Job, 2 Job отменяется, 1 Job выполняется после выполнения первой Job
#     concurrency:
#       group: example_matrix
      
#     ----------------------------------------------------------------------------------------------      
#     #запускаются 2 Jobs параллельно и выполняются параллельно, следующие 2 Jobs запускаются после первых и выполняются параллельно
#     concurrency: example_matrix

    runs-on: ubuntu-latest
    strategy:
      matrix:
        version-skiff: ["1", "2", "3", "4"]
    steps:
      - uses: actions/checkout@v3
      - name: print time
        run: date
      - name: cat files
        run: cat test2/file${{ matrix.version-skiff }}.txt
      - name: sleep
        run: sleep 12
      - name: echo
        run: |
          echo ${{ github.job.name }}
          echo -e "\n"
          echo ${{ github.job }}
          echo -e "\n"
          echo "action:"
          echo ${{ github.action == 'example_matrix' }}
          echo "job:"
          echo ${{ github.job == 'example_matrix' }}
      - name: print time
        run: date
