#working version with 'docker run...' 
name: Test nginx
on:
  workflow_dispatch:
  # push:
  #   branches: [ master, main ]

jobs:
  build:
    name: "Nginx"
    runs-on: ubuntu-latest
    services:
      nginx-service:
        image: nginx
        ports: 
          - 80:80
    
    steps:
      - name: debug curl
        run: |
          telnet localhost 80
        continue-on-error: true
    
      - name: debug telnet
        run: |
          curl localhost:80
        continue-on-error: true